"""Harmonic moment recursions over a PARTIAL range, for the finite arc.

:mod:`nova.biot.elliptic` builds the moment families the full-turn polygon
reduction contracts against, all of them over the whole quarter range
``a in [0, pi/2]``.  A finite arc stops at an interior amplitude, and this module
is what changes when it does.

Less changes than the paper's own packaging suggests, and the reason is worth
stating because it decides how much of the shipped reduction survives.  Of the
three families only ONE has a recursion that knows where the range ends:

* :func:`nova.biot.elliptic.harmonic_root_moments` folds ``Delta^2`` back under
  the integral, and ``Delta^2 = (1 + k'^2)/2 + (k^2/2) cos 2a`` is an identity of
  the integrand.  It holds at any limit, unchanged.
* :func:`nova.biot.elliptic.harmonic_pole_moments` multiplies its own pole factor
  back and splits the product of two cosines.  Also an identity of the integrand,
  also unchanged -- though its closure needs re-arguing, see below.
* :func:`harmonic_moments` here is the one that moves.  Its recursion comes from
  ``[sin 2na Delta]`` vanishing at BOTH ends of the quarter range, and at an
  interior limit the upper end does not vanish: the relation gains a source term
  and stops being homogeneous.

    (2n + 1) k^2 P(n+1) + 4n (1 + k'^2) P(n) + (2n - 1) k^2 P(n-1)
        = 4 sin(2 n alpha) Delta(alpha)

That one change is structural rather than cosmetic, and it invalidates the
complete family's whole stability argument rather than amending it.  The complete
moments are the MINIMAL solution of a homogeneous relation -- they decay
geometrically, being the Fourier series of a function analytic on the closed range
-- which is what makes a downward recursion on the ratios the right route there.
Cut the range short and the endpoint puts a jump into the periodic extension, the
moments decay only as ``1/n``, and NO branch of the homogeneous relation describes
them: minimality is not available to be exploited.

So the family is not recursed downward at all here.  It is SOLVED, as a
tridiagonal system whose diagonal ``4n(1 + k'^2)`` exceeds its off-diagonals
summing to ``4n k^2`` at every parameter, closed a fixed number of orders past
the last one wanted.  What that closure costs is set by the system's contraction
ratio, and the ratio is where the second direction comes from: it is
``[(1 + k'^2) - sqrt((1 + k'^2)^2 - k^4)]/k^2``, which is 0.17 for a distant
target and reaches ONE as the modulus does -- and a target on the source ring is
the common configuration, not an exotic one.  There the relation has the exact
solution ``(-1)^n`` in its kernel, so nothing damps a closure at all.

The upward recursion covers exactly that end, for the same reason and by the same
number: what grows going up is the reciprocal of that ratio, so the direction the
solve loses is the one the recursion gains.  Its two seeds are the incomplete
integrals directly, ``P_0 = F`` and ``P_1 = F - 2(F - E)/k^2``.  The switch
between them is measured rather than argued, and so is the headroom -- see the
two constants below.

The pole family's own closure needs the same re-argument and survives it: ITS
wanted solution no longer decays either, but its closure error still does, by
``(1 + 2 shift) - sqrt((1 + 2 shift)^2 - 1)`` per order, and the caller only takes
that route for a root far enough past the range for the decay to bite.  What the
family does need is its SEED, and that is the one special function a partial range
adds: :func:`cn_pole_moment` and :func:`sn_pole_moment` here are the interior-
amplitude counterparts of :mod:`nova.biot.elliptic`'s, and each is one incomplete
integral of the third kind at a pole argument the shift supplies exactly.

The source term is built from the amplitude's own sine and cosine rather than
from the amplitude, and that is what makes the quarter turn EXACT rather than
nearly right.  ``sin 2n alpha`` is generated by the Chebyshev recursion from
``sin 2 alpha = 2 sin alpha cos alpha``; handed the exact pair ``(1, 0)`` that
seed is exactly zero, every harmonic after it is exactly zero, and the system
collapses onto the homogeneous one the complete family solves.  Taken instead as
``sin(n pi)`` from a floating-point right angle the seed is 1e-16 and the arc
would miss the ring it closes onto by that much at every order.
"""

from __future__ import annotations

import numpy as np

from nova.biot.incompleteelliptic import incomplete_kind, incomplete_pole

__all__ = [
    "HEADROOM",
    "SWITCH",
    "cn_pole_moment",
    "harmonic_moments",
    "harmonic_source",
    "sn_pole_moment",
]

# Orders carried past the last one wanted before the tridiagonal system is closed.
# The closure's error decays on the way back down by the system's own contraction
# ratio, and that ratio reaches one AS THE MODULUS DOES, so the headroom is set by
# the switch below rather than by a decay of one half: at the switch it is 0.774
# per order, which needs a hundred and thirty of them to bury a closure the
# asymptotic moment has already reduced to 1e-6.  Measured over a sweep of
# amplitude and parameter against panelled quadrature, the family converges at
# 130 -- 1.2e-13 at 110, 1.3e-14 at 120, and 8.7e-15 from 130 on, which is the
# incomplete first kind's own floor rather than the solve's.
HEADROOM = 130

# Where the family leaves the tridiagonal solve for the upward recursion.  Set by
# the same sweep: the solve stops contracting as the modulus reaches one and the
# recursion stops growing at the same point, so each covers what the other cannot.
# Measured worst case over the sweep is 8.7e-15 here against 1.5e-13 at 0.997 and
# 1.3e-7 with too little headroom on either side of it.
SWITCH = 0.99


def harmonic_source(sine, cosine, count, *, xp=np):
    """Return ``[sin 0, sin 2a, sin 4a, ...]`` from the amplitude's own pair.

    The boundary term the partial range leaves in every moment relation, and the
    only place the amplitude enters the system other than through its first
    moment.  Generated by the Chebyshev recursion ``s(n+1) = 2 cos(2a) s(n) -
    s(n-1)`` from ``sin 2a = 2 sin a cos a``, whose errors grow linearly in the
    order and are bounded by the sines themselves.

    Taking the pair from the caller rather than the amplitude is what makes a
    quarter turn exact: ``sin 2a`` is then exactly zero, so every harmonic is, and
    the system reduces to the homogeneous one the complete family satisfies.
    ``sin(n pi)`` of a floating-point right angle is 1e-16 times the order
    instead, and the arc would then differ from the ring it closes onto by a
    source term that is not there.
    """
    sine = xp.asarray(sine)
    cosine = xp.asarray(cosine) + xp.zeros_like(sine)
    # the doubled angle as a product and a difference of squares, so a pair that
    # is exact stays exact through both
    doubled_sine = 2.0 * sine * cosine
    doubled_cosine = (cosine - sine) * (cosine + sine)
    source = [xp.zeros_like(doubled_sine), doubled_sine]
    for order in range(1, count - 1):
        source.append(2.0 * doubled_cosine * source[order] - source[order - 1])
    return source[:count]


def harmonic_moments(
    amplitude,
    parameter,
    count: int,
    *,
    complement=None,
    sine=None,
    cosine=None,
    xp=np,
    headroom: int = HEADROOM,
    switch: float = SWITCH,
):
    """Return ``[P_0, ...]``, ``P_n = integral_0^amplitude cos(2 n a)/Delta da``.

    The partial-range counterpart of
    :func:`nova.biot.elliptic.harmonic_moments`, and the family every numerator
    the arc reduction builds is contracted against.  ``P_0`` is the incomplete
    integral of the first kind and comes from
    :func:`nova.biot.incompleteelliptic.incomplete_kind`; everything above it is
    the tridiagonal solve the module docstring derives, run by the Thomas sweep
    and closed ``headroom`` orders past the last moment wanted.

    Only ABSOLUTE accuracy of order ``eps P_0`` is wanted, as in the complete
    case: the high harmonics are small and multiply coefficients no larger than
    the low ones, so an error tiny beside ``P_0`` is tiny beside the contraction
    however large it is beside ``P_n`` itself.  That is what lets one route serve
    the whole parameter range here where the complete family needs two.

    ``complement`` supplies ``k'^2`` and ``sine``/``cosine`` the amplitude's own
    pair; both are the quantities a caller forms exactly from its geometry, and
    both matter for the same reason -- see
    :func:`nova.biot.incompleteelliptic.incomplete_kind`.
    """
    amplitude = xp.asarray(amplitude)
    parameter = xp.asarray(parameter) + xp.zeros_like(amplitude)
    if complement is None:
        complement = 1.0 - parameter
    complement = xp.asarray(complement) + xp.zeros_like(amplitude)
    if sine is None:
        sine = xp.sin(amplitude)
    if cosine is None:
        cosine = xp.cos(amplitude)
    sine = xp.asarray(sine) + xp.zeros_like(amplitude)
    cosine = xp.asarray(cosine) + xp.zeros_like(amplitude)

    first, second = incomplete_kind(
        amplitude, complement, sine=sine, cosine=cosine, parameter=parameter, xp=xp
    )
    top = count + headroom
    # Delta at the amplitude, as the radical of the two exact quantities rather
    # than of 1 - k^2 sin^2 a: at a target on the source ring the second is a
    # cancellation and the first is not
    edge = xp.sqrt(complement + parameter * cosine * cosine)
    source = harmonic_source(sine, cosine, top + 2, xp=xp)
    degenerate = parameter > switch

    # UPWARD, as printed, from the two seeds the elliptic integrals give directly:
    # P_1 = F - 2(F - E)/k^2, the second sine moment being (F - E)/k^2. It divides
    # by k^2 once per order and grows by the recursion's dominant branch, so it is
    # the route only where that branch is nearly one -- which is where the other
    # route stops contracting, so between them they span the range.
    held = xp.where(degenerate, parameter, 1.0)
    held_complement = xp.where(degenerate, complement, 0.0)
    upward = [first, first - 2.0 * (first - second) / held]
    for order in range(1, count - 1):
        upward.append(
            (
                4.0 * source[order] * edge
                - 4.0 * order * (1.0 + held_complement) * upward[order]
                - held * (2 * order - 1) * upward[order - 1]
            )
            / (held * (2 * order + 1))
        )

    # DOWNWARD, as the tridiagonal solve the module docstring derives, closed
    # ``headroom`` orders past the last moment wanted -- on the ASYMPTOTIC moment
    # rather than on zero.  Integrating the definition by parts twice gives
    # ``P_n = sin 2na/(2n Delta) + O(1/n^2)`` at the amplitude, and using it costs
    # nothing: it is one term of a series this routine has already formed.
    held = xp.where(degenerate, 1.0, parameter)
    held_complement = xp.where(degenerate, 0.0, complement)
    diagonal = 4.0 * (1.0 + held_complement)
    closure = source[top + 1] / (2.0 * (top + 1) * edge)
    pivot = diagonal
    carried = [held * 3.0 / pivot]
    solution = [(4.0 * source[1] * edge - held * first) / pivot]
    for order in range(2, top + 1):
        pivot = order * diagonal - held * (2 * order - 1) * carried[-1]
        carried.append(held * (2 * order + 1) / pivot)
        solution.append(
            (4.0 * source[order] * edge - held * (2 * order - 1) * solution[-1]) / pivot
        )
    downward: list = [None] * (top + 1)
    downward[top] = solution[top - 1] - carried[top - 1] * closure
    for order in range(top - 1, 0, -1):
        downward[order] = solution[order - 1] - carried[order - 1] * downward[order + 1]
    downward[0] = first
    return [
        xp.where(degenerate, upward[order], downward[order]) for order in range(count)
    ]


def cn_pole_moment(shift, parameter, sine, cosine, *, complement=None, xp=np):
    """Return ``integral_0^phi da/((cos^2 a + shift) Delta)``, a family's seed.

    The interior-amplitude counterpart of
    :func:`nova.biot.elliptic.cn_pole_moment`, and the same reduction to one
    special function: ``cos^2 a + shift = (1 + shift)(cos^2 a + p sin^2 a)`` with
    ``p = shift/(1 + shift)``, whose complement ``1/(1 + shift)`` is exact, so no
    characteristic is formed and none is lost.

    The root sits past the FAR end of the range, and at a partial amplitude that
    end is OUTSIDE it: a vanishing shift makes the complete integral diverge and
    leaves this one finite, right up to the quarter turn where the two meet.  The
    convention at a shift of exactly zero is the complete routine's -- see
    :func:`nova.biot.incompleteelliptic.incomplete_pole`.
    """
    shift = xp.asarray(shift)
    if complement is None:
        complement = 1.0 - xp.asarray(parameter)
    return incomplete_pole(shift / (1.0 + shift), complement, sine, cosine, xp=xp) / (
        1.0 + shift
    )


def sn_pole_moment(shift, parameter, sine, cosine, *, complement=None, xp=np):
    """Return ``integral_0^phi da/((sin^2 a + shift) Delta)``, the mirror seed.

    ``sin^2 a + shift = shift (cos^2 a + p sin^2 a)`` with ``p = (1 + shift)/
    shift``, so a root just past the ``a = 0`` end is a LARGE pole argument, as it
    is for :func:`nova.biot.elliptic.sn_pole_moment`.

    This is the orientation the arc reaches at every corner rather than
    occasionally, because the range always STARTS at ``a = 0`` -- the root is
    inside the layer the integral is concentrated in, whatever the amplitude -- and
    it is the one the symmetric forms cannot take as printed.  What carries it is
    the reflection onto ``k'^2/p``; see
    :func:`nova.biot.incompleteelliptic.incomplete_pole`.
    """
    shift = xp.asarray(shift)
    if complement is None:
        complement = 1.0 - xp.asarray(parameter)
    live = shift > 0.0
    held = xp.where(live, shift, 1.0)
    return xp.where(
        live,
        incomplete_pole((1.0 + held) / held, complement, sine, cosine, xp=xp) / held,
        0.0,
    )
