repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
