repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--extras", "ferritic", 
               "--extras", "graphics", 
               "--extras", "numba", 
               "--extras", "optimize", 
               "--extras", "structural", 
               "--extras", "test", 
               "--extras", "thermofluids", 
               "--extras", "vtk",
               "--without-hashes", 
               "-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.270
    hooks:
      - id: ruff   
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
