[build-system]
requires = ["setuptools", "wheel", "versioneer[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["nova"]

[project]
name = "nova"
description = "Equilibrium generation and inference"
authors = [
  {name = "Simon McIntosh"},
  {email = "simon.mcintosh@iter.org"}
]
readme = "README.md"
license = {text = "ITER GIP"}
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: ITER GIP License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering :: Fusion",
]
dynamic = ["version"]
keywords = ["equilibrium", "generation", "reconstruction", "inference", "plasma", "Biot-Savart", "mesh-free"]

dependencies = [
  "alphashape",
  "appdirs",
  "click",
  "cython",
  "bokeh",
  "dask[distributed]",
  "descartes",
  "fabric",
  "fortranformat",
  "gitpython",
  "meshio",
  "moviepy", 
  "netCDF4",
  "numba",
  "numdifftools", 
  "numpy",
  "pandas>=1.5",
  "pylops>=2.0",
  "pyperf",
  "pyvista",
  "pyquaternion",
  "quadpy",
  "rdp",
  "seaborn",
  "scipy",
  "scikit-learn",
  "shapely",
  "tqdm",
  "vedo>=2022.4",
  "wheel",
  "xarray",
  "xxhash"
]
 
[project.optional-dependencies]
ansys = [
  "ansys-dpf-core", 
  "ansys-dpf-post", 
  "openpyxl"
]
cuda = [
  "cupy-cuda115"
]
dev = [ 
  "nova[docs, mesh, optimize, spyder, tests]",
]	
docs = [
  "pandoc", 
  "jupyter"
]
full = [
  "nova[ansys, docs, mesh, optimize, plan, spyder, test, thermofluids]"
]
mesh = [
  "alphashape",
  "gmsh", 
  "pygmsh", 
  "tetgen", 
  "trimesh"
]
optimize = [
  "nlopt" 
]
plan = [
  "python-dateutil"
]
spyder = [
  "spyder", 
  "spyder-unittest", 
  "spyder-line-profiler", 
  "spyder-memory-profiler", 
  "pylsp-mypy",
  "line_profiler",
  "pandas-stubs",
]
test = [
  "coverage2clover", 
  "pytest", 
  "pytest-cov", 
  "pytest-xdist", 
  "tuna",
  "lizard", 
  "mypy",
  "asv", 
  "virtualenv", 
  "snakeviz"
]
thermofluids = [
  "ftputil", 
  "coolprop", 
  "tables", 
  "xlrd"
]

[project.scripts]
benchmark = "nova.scripts.benchmark:benchmark"
extrapolate = "nova.imas.scripts:extrapolate"

[project.urls]
Homepage = "https://git.iter.org/projects/EQ/repos/nova/"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "nova/_version.py"
versionfile_build = "nova/_version.py"
tag_prefix = ""
parentdir_prefix = "nova-"

[tool.pytest.ini_options]
testpaths = [
  "tests",
  "nova/imas"
]
filterwarnings = [
  "once::Warning",
  "ignore::DeprecationWarning",
  "ignore::FutureWarning"
]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true 
ignore_missing_imports = true

[tool.coverage.run]
omit = [
  "nova/ansys/*", 
  "nova/assembly/*", 
  "nova/design/*", 
  "nova/development/*", 
  "nova/dina/*", 
  "nova/obsolete/*",
  "nova/projects/*", 
  "nova/scripts/*", 
  "nova/thermalhydralic/*", 
  "nova/utilities/*"
]
