[build-system]
requires = ["setuptools", "wheel", "versioneer-518"]
build-backend = "setuptools.build_meta"

[tool.pylsp-mypy]
enabled = false
live_mode = false
strict = true
dmypy = true
ignore_missing_imports = true

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "scipy.*"
ignore_missing_imports = true
