[build-system]
requires = ["setuptools", "wheel", "versioneer[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["nova"]

[project]
name = "nova"
description = "Equilibrium generation and inference"
authors = [
  {name = "Simon McIntosh"},
  {email = "simon.mcintosh@iter.org"}
]
readme = "README.md"
license = {text = "ITER GIP"}
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: ITER GIP License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering :: Fusion",
]
dynamic = ["version"]
keywords = ["equilibrium", "generation", "reconstruction", "inference", "plasma", "Biot-Savart", "mesh-free"]

dependencies = [
  "appdirs",
  "click",
  "contourpy",
  "cython",
  "fsspec",
  "gitpython",
  "netCDF4",
  "networkx",
  "numpy",
  "pandas>=2.0",
  "pytest",
  "scipy",
  "shapely>=2.0",
  "tqdm",
  "xarray",
  "xxhash",
]
 
[project.optional-dependencies]
ansys = [
  "ansys-dpf-core", 
  "ansys-dpf-post", 
  "fortranformat",
  "openpyxl",
]
complete = [
  "nova[ferritic, optimize, structural, thermofluids]"
]
cuda = [
  "cupy-cuda115",
]
develop = [
  "nova[complete, document, diagnostics, graphics, ide, jit, mesh, optimize, ssh, test, vtk]",
]
diagnostics = [
  "asv", 
  "line_profiler",
  "lizard", 
  "mypy",
  "pandas-stubs",
  "pylsp-mypy",
  "pyperf",
  "snakeviz",
  "tuna",
  "virtualenv", 
]
document = [
  "pandoc",
  "sphinx", 
]
ferritic = [
  "vedo>=2022.4", 
  "scikit-learn",
]
graphics = [
  "bokeh",
  "descartes",
  "matplotlib",
  "moviepy", 
  "seaborn",
]
ide = [
  "jupyter",
  "spyder", 
  "spyder-unittest", 
  "spyder-line-profiler", 
  "spyder-memory-profiler", 
]
jit = [
  "numba",
]
mesh = [
  "alphashape",
  "gmsh", 
  "meshio",
  "pygmsh", 
  "tetgen", 
  "trimesh",
]
optimize = [
  "nlopt", 
  "pylops>=2.0",
  "scikit-learn",
]
plan = [
  "python-dateutil",
]
ssh = [
  "fabric",
]
structural = [
  "pyquaternion",
]
test = [
  "coverage2clover", 
  "pytest-cov", 
  "pytest-xdist", 
]
thermofluids = [
  "coolprop", 
  "ftputil", 
  "openpyxl",
  "tables", 
  "xlrd",
]
vtk = [
  "pyvista",
  "vedo>=2022.4",
]

[project.scripts]
benchmark = "nova.scripts.benchmark:benchmark"
extrapolate = "nova.imas.scripts:extrapolate"
filepath = "nova.database.scripts:filepath"
configure = "nova.scripts.configure:configure"

[project.urls]
Homepage = "https://git.iter.org/projects/EQ/repos/nova/"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "nova/_version.py"
versionfile_build = "nova/_version.py"
tag_prefix = ""
parentdir_prefix = "nova-"

[tool.pytest.ini_options]
addopts = "-rfEs --doctest-modules"
norecursedirs = ".git __pycache__"
testpaths = [
  "tests",
  "nova/imas/database.py", 
  "nova/imas/equilibrium.py", 
  "nova/imas/extrapolate.py",
  "nova/imas/machine.py", 
  "nova/imas/operate.py",
  "nova/imas/pulsedesign.py", 
]
 filterwarnings = [
  "once::Warning",
  "ignore:open:DeprecationWarning:imas",
]

[tool.mypy]
warn_return_any = true
warn_unused_configs = false
ignore_missing_imports = true
implicit_reexport = false

[tool.pylsp-mypy]
enabled = true
live_mode = false
dmypy = true
strict = false

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["src"]
omit = [
  "nova/ansys/*", 
  "nova/assembly/*", 
  "nova/design/*", 
  "nova/development/*", 
  "nova/dina/*", 
  "nova/obsolete/*",
  "nova/projects/*", 
  "nova/scripts/*", 
  "nova/thermalhydralic/*", 
  "nova/utilities/*"
]
