r"""Traced free-boundary flux map behind the forward equilibrium solve.

This is the implementation-level operator of
:class:`nova.equilibrium.forward.ForwardProfile`, not a second public
equilibrium problem. It carries one write-then-read cycle of the
free-boundary map: a trial total poloidal flux is read for its topology, the
prescribed flux functions are evaluated on the domains that read labels, and
the resulting cell currents are mapped back to flux through the precomputed
coupling operators. A root of :meth:`ForwardFluxOperator.residual` is a
free-boundary equilibrium.

The supplied source reaches the current image unchanged. There is no net
plasma current on this operator and no place to put one: the amplitude the
caller supplied is the amplitude the map uses, so a current image can never
be silently rescaled to meet a target.

The operator is immutable host-and-device state that the traced maps close
over rather than a traced argument, so a flux function may be any callable —
an interpolant carrying device arrays or a closed-form profile. Everything
that varies across a batch (the trial flux, the conductor currents) is an
explicit argument, which is what ``jit``, ``vmap`` and ``grad`` need.

All fluxes are total poloidal fluxes, :math:`\Phi = 2 \pi R A_\phi` in Wb,
concatenated over the plasma grid nodes followed by the wall nodes.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field

import jax
import jax.numpy as jnp

from nova.biot.target import FluxTarget
from nova.equilibrium.domain import DomainMasks
from nova.equilibrium.source import ForwardSource
from nova.equilibrium.stencil_mesh import MomentGeometry
from nova.equilibrium.topology import Topology, TopologyState

__all__ = ["ForwardFluxOperator"]


@dataclass
class ForwardFluxOperator:
    """Map a trial poloidal flux to the flux its plasma current generates."""

    grid: FluxTarget
    wall: FluxTarget
    source: ForwardSource
    external_current: jnp.ndarray = field(repr=False)
    area: jnp.ndarray = field(repr=False)
    polarity: int = 1
    inside_material: jnp.ndarray | None = field(repr=False, default=None)
    moment_geometry: MomentGeometry | None = field(repr=False, default=None)

    def __post_init__(self):
        """Build the topology read and default the material mask."""
        self.topology = Topology(self.grid.null, self.wall.null)
        self.external_current = jnp.asarray(self.external_current)
        self.area = jnp.asarray(self.area)
        if self.inside_material is None:
            self.inside_material = jnp.ones(self.grid.node_number, dtype=bool)
        else:
            self.inside_material = jnp.asarray(self.inside_material, dtype=bool)
        if self.area.shape != (self.grid.node_number,):
            raise ValueError("area must carry one control area per grid node")
        if self.inside_material.shape != (self.grid.node_number,):
            raise ValueError("inside_material must carry one flag per grid node")
        if (
            self.moment_geometry is not None
            and len(self.moment_geometry.polygons) != self.grid.node_number
        ):
            raise ValueError("moment geometry must carry one polygon per grid node")

    @property
    def node_number(self) -> int:
        """Return the length of the concatenated grid and wall flux vector."""
        return self.grid.node_number + self.wall.node_number

    @property
    def radius(self) -> jax.Array:
        """Return the radius [m] of every plasma grid node."""
        return self.grid.coordinate[:, 0]

    def _current(self, current) -> jax.Array:
        """Return the conductor currents one evaluation should use."""
        return self.external_current if current is None else jnp.asarray(current)

    def external(self, current=None) -> jax.Array:
        """Return the flux map [Wb] of every conductor but the plasma."""
        conductor = self._current(current)
        return jnp.r_[self.grid.external(conductor), self.wall.external(conductor)]

    def read(self, psi) -> tuple[DomainMasks, TopologyState]:
        """Return the domain labels and axis/separatrix state of a trial flux."""
        return self.topology.read(psi, self.polarity, self.inside_material)

    def shared_node_flux(self, psi) -> jax.Array:
        """Evaluate the plasma-grid flux on fixed atomic shared nodes."""
        if self.moment_geometry is None:
            raise ValueError("moment geometry is required for shared-node flux")
        grid_flux, _wall_flux = self.topology.split_flux_map(psi)
        return self.moment_geometry.shared_node_flux(grid_flux)

    def cell_current(self, psi) -> jax.Array:
        """Return the per-cell plasma current [A] a trial flux drives."""
        masks = self.read(psi)[0]
        return self.source.cell_current(self.radius, self.area, masks)

    def internal(self, psi) -> jax.Array:
        """Return the flux map [Wb] generated by the plasma current."""
        current = self.cell_current(psi)
        return jnp.r_[self.grid.internal(current), self.wall.internal(current)]

    def __call__(self, psi, current=None) -> jax.Array:
        """Return the total poloidal flux [Wb] one write-then-read cycle gives."""
        return self.external(current) + self.internal(psi)

    def residual(self, psi, current=None) -> jax.Array:
        """Return the free-boundary flux residual of a trial flux map."""
        return psi - self(psi, current)

    def flux_map(self, current=None) -> Callable[[jax.Array], jax.Array]:
        """Return the fixed-point map ``psi -> g(psi)`` at one conductor state.

        The external contribution is evaluated once and captured, so a
        fixed-point ladder pays for the plasma coupling alone.
        """
        external = self.external(current)

        def mapped(psi: jax.Array) -> jax.Array:
            """Return the free-boundary flux map of one trial flux."""
            return external + self.internal(psi)

        return mapped
