!===============================================================================
! 15.05.2018 - Fabian Krajewski CADFEM - V2_2
! 	Macro to run all the emag analyses
! 
!	arg1
!	Revision: 	Defines the gap version for the model
!
!	arg2
!	LOADCASE: 	1: TF_ONLY
!			2: SOD
!			3: EOB
!	arg3
!	Scenario:	0: 15MA
!			1: 5MA
! 
!===============================================================================

*USE,  './MACRO/MAGNET_MAGNO.mac', arg1, 1, arg2, arg3			! EMAG Analysis					!


	